---
- hosts: docker
  vars_files:
    - secrets.yml
  tasks:
  - name: Include common role
    include_role:
      name: common

  - name: Include docker role
    include_role:
      name: docker

  - name: Include influxdb role
    include_role:
      name: influxdb

  - name: Include grafana role
    include_role:
      name: grafana

  - name: Include plex role
    include_role:
      name: plex

  - name: Include gitlab role
    include_role:
      name: gitlab
