---
- hosts: docker
  tasks:
  - name: Include common role
    include_role:
      name: common

  - name: Include docker role
    include_role:
      name: docker

  - name: Include plex role
    include_role:
      name: plex
