---
- name: Create plex docker container
  docker_container:
    name: plex
    image: plexinc/pms-docker
    state: started
    restart: True
    network_mode: host
    restart_policy: always
    env:
      TZ: America/New_York
    volumes:
      - /plex-volumes/config:/config
      - /plex-volumes/transcode:/transcode
      - /plex-volumes/data:/data:ro
  become: True
