---
- name: Create plex docker container
  docker_container:
    name: plex
    image: plexinc/pms-docker:plexpass
    state: started
    restart: True
    network_mode: host
    restart_policy: always
    env:
      TZ: America/New_York
    volumes:
      - /docker-volumes/plex/config:/config
      - /docker-volumes/plex/transcode:/transcode
      - /docker-volumes/plex/data:/data:ro
  become: True
