---
- name: Update apt cache
  apt:
    update_cache: True
  become: True

- name: Upgrade apt distribution
  apt:
    upgrade: True
  become: True

- name: Install apt-transport-https
  package:
    name: apt-transport-https
    state: latest
  become: True

- name: Install software-properties-common
  package:
    name: software-properties-common
  become: True

- name: Install unattended-upgrades
  package:
    name: unattended-upgrades
    state: latest
  become: True
